export type CharacterFormValues = {
    aiName: string;
    avatarUrl?: string;
    appearanceReferenceUrl?: string;
    appearanceReferenceObjectPath?: string;
    posterUrl?: string;
    visibility: string;
    role?: string;
    character?: string;
    personalityTraits?: string;
    biography?: string;
    speechStyle?: string;
    relationshipContext?: string;
    memoryNotes?: string;
    responseBoundaries?: string;
    systemContext?: string;
    rule?: string;
    styleExamples?: string;
    imageEnabled: boolean;
    photoKeywords?: string;
    activityKeywords?: string;
    imagePromptTemplate?: string;
    personaFeedEnabled: boolean;
    personaFeedMinIntervalHours: number;
    personaFeedMaxIntervalHours: number;
    personaFeedWindowStart?: string;
    personaFeedWindowEnd?: string;
    personaFeedTimezone: string;
};

export type CharacterPayload = {
    aiName: string;
    avatarUrl: string | null;
    appearanceReferenceUrl: string | null;
    appearanceReferenceObjectPath: string | null;
    posterUrl: string | null;
    visibility: string;
    role: string | null;
    character: string | null;
    personalityTraits: string;
    biography: string | null;
    speechStyle: string | null;
    relationshipContext: string | null;
    memoryNotes: string | null;
    responseBoundaries: string | null;
    systemContext: string | null;
    rule: string | null;
    styleExamples: string;
    imageEnabled: boolean;
    imageTriggerRules: string;
    imagePromptTemplate: string | null;
    personaFeedEnabled: boolean;
    personaFeedMinIntervalHours: number;
    personaFeedMaxIntervalHours: number;
    personaFeedWindowStart: string | null;
    personaFeedWindowEnd: string | null;
    personaFeedTimezone: string;
};
